apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: my-hotel-service
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: my-hotel-service
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  type: NodePort
  selector:
    app: mongo