apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
  namespace: my-hotel-service
spec:
  selector:
    matchLabels:
      app: db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
        - name: db-service
          image: cooco119/my-hotel-service.db-service:latest
          ports:
            - containerPort: 5001
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: my-hotel-service
spec:
  ports:
    - port: 5001
      targetPort: 5001
  type: NodePort
  selector:
    app: db-service