apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-service
  namespace: my-hotel-service
spec:
  selector:
    matchLabels:
      app: queue-service
  replicas: 1
  template:
    metadata:
      labels:
        app: queue-service
    spec:
      containers:
        - name: queue-service
          image: cooco119/my-hotel-service.queue-service:latest
          ports:
            - containerPort: 5002
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: queue-service
  namespace: my-hotel-service
spec:
  ports:
    - port: 5002
      targetPort: 5002
  type: NodePort
  selector:
    app: queue-service